= metanorma-plateau: Metanorma processor for Plateau project, Japanese Ministry of Land, Infrastructure, Transport and Tourism

image:https://img.shields.io/gem/v/metanorma-plateau.svg["Gem Version", link="https://rubygems.org/gems/metanorma-plateau"]
image:https://github.com/metanorma/metanorma-plateau/workflows/rake/badge.svg["Build Status", link="https://github.com/metanorma/metanorma-plateau/actions?workflow=rake"]
image:https://codeclimate.com/github/metanorma/metanorma-plateau/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/metanorma-plateau"]
image:https://img.shields.io/github/issues-pr-raw/metanorma/metanorma-plateau.svg["Pull Requests", link="https://github.com/metanorma/metanorma-plateau/pulls"]
image:https://img.shields.io/github/commits-since/metanorma/metanorma-plateau/latest.svg["Commits since latest",link="https://github.com/metanorma/metanorma-plateau/releases"]

== Functionality

This gem processes https://www.metanorma.com[Metanorma documents] following
the Metanorma model for generating MLIT Plateau standards.

The gem is basically the https://github.com/metanorma/metanorma-jis gem, with some tweaking of rendering to meet the particular requirements of the MLIT Plateau project.

It provides the following functions:

. Compiles Metanorma input into the Metanorma-Plateau XML format
. Validates XML output against the Metanorma-Plateau document model
** Errors are reported to console against the XML, and are intended for users to
check that they have provided all necessary components of the
document.
. Metanorma-Plateau XML is then converted into desired output formats.

The following outputs are supported:

* Primary: the canonical Metanorma-JIS XML representation (`.xml`).
* Secondary: the Metanorma-JIS XML representation is processed to generate the following outputs
as end deliverable JIS documents.
** HTML (`.html`)
** PDF (`.pdf`)

== Structure

This gem inherits from the https://github.com/metanorma/metanorma-jis
gem, and aligns closely to it.


=== Quickstart

Please see https://www.metanorma.com for instructions to get started.

You will need to setup your Git credentials for bundler or for HTTPS in order
to fetch the software. Please refer to the following articles for details:

* https://depfu.com/blog/2017/08/02/bundler-and-private-dependencies[Setting up bundler for private dependencies]
* https://bundler.io/v1.16/bundle_config.html#CREDENTIALS-FOR-GEM-SOURCES[Bundler credentials for gem sources]
* https://help.github.com/articles/caching-your-github-password-in-git[GitHub - Caching your GitHub credentials in Git]


== Usage

Using the `metanorma` CLI:

[source,console]
----
$ metanorma --type plateau a.adoc                   # output HTML
$ metanorma --type plateau --extensions html a.adoc # output just HTML
$ metanorma --type plateau --extensions xml a.adoc  # output Metanorma XML
----


== Authoring

Please refer to the Metanorma-ISO documentation for general documentation.

* Metanorma-ISO general documentation: https://www.metanorma.com/software/metanorma-iso/

* Metanorma-ISO guidance: https://www.metanorma.com/software/metanorma-iso/docs/guidance/


== Documentation

See https://www.metanorma.com/author/iso/[Write ISO documents with Metanorma]

== Examples

* Example documents are avalable at the https://github.com/metanorma/mn-samples-plateau[mn-samples-plateau] repository.
* Document templates are available at the https://github.com/metanorma/mn-templates-plateau[mn-templates-plateau] repository.

